name: RELEASE
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.?[0-9]*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test:
    uses: ./.github/workflows/qa-coverage.yml
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
              echo "APP_VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Version Check
        if: ${{ github.ref_name != format('v{0}',env.APP_VERSION) }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('App version in tag mismatch real code version!!! (${{ format('v{0}', env.APP_VERSION) }} != ${{ github.ref_name }})')
      - run: deno bundle src/index.ts -- api-mockr-${{ env.APP_VERSION }}.ts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_CREATION }}
          files: api-mockr-${{ env.APP_VERSION }}.ts